# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tauTest <- function(arr1, arr2, length) {
    .Call('gemmR_tauTest', PACKAGE = 'gemmR', arr1, arr2, length)
}

fitValues <- function(betas, data) {
    .Call('gemmR_fitValues', PACKAGE = 'gemmR', betas, data)
}

corRcpp <- function(x, y) {
    .Call('gemmR_corRcpp', PACKAGE = 'gemmR', x, y)
}

gemmFitRcpp <- function(n, betas, data, p, kCor, correction) {
    .Call('gemmR_gemmFitRcpp', PACKAGE = 'gemmR', n, betas, data, p, kCor, correction)
}

gemmFitRcppI <- function(n, betas, data, p, kCor, correction) {
    .Call('gemmR_gemmFitRcppI', PACKAGE = 'gemmR', n, betas, data, p, kCor, correction)
}

sortIt <- function(x) {
    .Call('gemmR_sortIt', PACKAGE = 'gemmR', x)
}

genAlg <- function(metricbeta, nbeta, nsuperelites, p, gens, bestmodels, seedmetric) {
    .Call('gemmR_genAlg', PACKAGE = 'gemmR', metricbeta, nbeta, nsuperelites, p, gens, bestmodels, seedmetric)
}

