# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kt <- function(arr1, arr2, length) {
    .Call('gemmR_kt', PACKAGE = 'gemmR', arr1, arr2, length)
}

fitValues <- function(betas, data) {
    .Call('gemmR_fitValues', PACKAGE = 'gemmR', betas, data)
}

corRcpp <- function(x, y) {
    .Call('gemmR_corRcpp', PACKAGE = 'gemmR', x, y)
}

gemmFitRcpp <- function(n, betas, data, p, kCor, pearson) {
    .Call('gemmR_gemmFitRcpp', PACKAGE = 'gemmR', n, betas, data, p, kCor, pearson)
}

gemmFitRcppI <- function(n, betas, data, p, kCor, getR) {
    .Call('gemmR_gemmFitRcppI', PACKAGE = 'gemmR', n, betas, data, p, kCor, getR)
}

sortIt <- function(x) {
    .Call('gemmR_sortIt', PACKAGE = 'gemmR', x)
}

genAlg <- function(metricbeta, nbeta, nsuperelites, p, reps, bestmodels, seedmetric) {
    .Call('gemmR_genAlg', PACKAGE = 'gemmR', metricbeta, nbeta, nsuperelites, p, reps, bestmodels, seedmetric)
}

rcpp_hello_world <- function() {
    .Call('gemmR_rcpp_hello_world', PACKAGE = 'gemmR')
}

