// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// tauTest
List tauTest(NumericVector arr1, NumericVector arr2, int length);
RcppExport SEXP gemmR_tauTest(SEXP arr1SEXP, SEXP arr2SEXP, SEXP lengthSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type arr1(arr1SEXP );
        Rcpp::traits::input_parameter< NumericVector >::type arr2(arr2SEXP );
        Rcpp::traits::input_parameter< int >::type length(lengthSEXP );
        List __result = tauTest(arr1, arr2, length);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// gemmFitRcppI
List gemmFitRcppI(int n, NumericMatrix betas, NumericMatrix data, int p, NumericVector kCor, CharacterVector correction, bool isTauB);
RcppExport SEXP gemmR_gemmFitRcppI(SEXP nSEXP, SEXP betasSEXP, SEXP dataSEXP, SEXP pSEXP, SEXP kCorSEXP, SEXP correctionSEXP, SEXP isTauBSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< int >::type n(nSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type betas(betasSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP );
        Rcpp::traits::input_parameter< int >::type p(pSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type kCor(kCorSEXP );
        Rcpp::traits::input_parameter< CharacterVector >::type correction(correctionSEXP );
        Rcpp::traits::input_parameter< bool >::type isTauB(isTauBSEXP );
        List __result = gemmFitRcppI(n, betas, data, p, kCor, correction, isTauB);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// genAlg
NumericMatrix genAlg(NumericMatrix metricbeta, int nbeta, int nsuperelites, int p, int gens, NumericMatrix bestmodels, bool seedmetric);
RcppExport SEXP gemmR_genAlg(SEXP metricbetaSEXP, SEXP nbetaSEXP, SEXP nsuperelitesSEXP, SEXP pSEXP, SEXP gensSEXP, SEXP bestmodelsSEXP, SEXP seedmetricSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type metricbeta(metricbetaSEXP );
        Rcpp::traits::input_parameter< int >::type nbeta(nbetaSEXP );
        Rcpp::traits::input_parameter< int >::type nsuperelites(nsuperelitesSEXP );
        Rcpp::traits::input_parameter< int >::type p(pSEXP );
        Rcpp::traits::input_parameter< int >::type gens(gensSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type bestmodels(bestmodelsSEXP );
        Rcpp::traits::input_parameter< bool >::type seedmetric(seedmetricSEXP );
        NumericMatrix __result = genAlg(metricbeta, nbeta, nsuperelites, p, gens, bestmodels, seedmetric);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
