# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tauTest <- function(arr1, arr2, length) {
    .Call(`_gemmR_tauTest`, arr1, arr2, length)
}

gemmFitRcppI <- function(n, betas, data, p, kCor, correction, isTauB) {
    .Call(`_gemmR_gemmFitRcppI`, n, betas, data, p, kCor, correction, isTauB)
}

genAlg <- function(metricbeta, nbeta, nsuperelites, p, gens, bestmodels, seedmetric) {
    .Call(`_gemmR_genAlg`, metricbeta, nbeta, nsuperelites, p, gens, bestmodels, seedmetric)
}

