# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kt <- function(arr1, arr2, length) {
    .Call('gemmR2_kt', PACKAGE = 'gemmR2', arr1, arr2, length)
}

fitValues <- function(betas, data) {
    .Call('gemmR2_fitValues', PACKAGE = 'gemmR2', betas, data)
}

corRcpp <- function(x, y) {
    .Call('gemmR2_corRcpp', PACKAGE = 'gemmR2', x, y)
}

gemmFitRcpp <- function(n, betas, data, p, kCor, pearson) {
    .Call('gemmR2_gemmFitRcpp', PACKAGE = 'gemmR2', n, betas, data, p, kCor, pearson)
}

gemmFitRcppI <- function(n, betas, data, p, kCor, getR) {
    .Call('gemmR2_gemmFitRcppI', PACKAGE = 'gemmR2', n, betas, data, p, kCor, getR)
}

sortIt <- function(x) {
    .Call('gemmR2_sortIt', PACKAGE = 'gemmR2', x)
}

genAlg <- function(metricbeta, nbeta, nsuperelites, p, reps, bestmodels, seedmetric) {
    .Call('gemmR2_genAlg', PACKAGE = 'gemmR2', metricbeta, nbeta, nsuperelites, p, reps, bestmodels, seedmetric)
}

