# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tauTest <- function(arr1, arr2, length) {
    .Call('gemmR_tauTest', PACKAGE = 'gemmR', arr1, arr2, length)
}

gemmFitRcppI <- function(n, betas, data, p, kCor, correction, isTauB) {
    .Call('gemmR_gemmFitRcppI', PACKAGE = 'gemmR', n, betas, data, p, kCor, correction, isTauB)
}

genAlg <- function(metricbeta, nbeta, nsuperelites, p, gens, bestmodels, seedmetric) {
    .Call('gemmR_genAlg', PACKAGE = 'gemmR', metricbeta, nbeta, nsuperelites, p, gens, bestmodels, seedmetric)
}

